### ISSUE TITLE
chroust ignores game_name

### ISSUE THREAD

**Issue by HollMax** [kkozlik/iquest-wr#17]
`; Name of the game. Used in title of all screens and also as Alt text for the logo
; Default: I.Quest
game_name=Viribus Unitis`
in metadata.ini had no effect on site title or alt text for logo.

**Comment by kkozlik** [comment]
Works for me.
Are you changing this option in metadata.ini in the top directory? 
Is it correctly updated in the Options DB table?
Are other options from metadata works for you? (e.g. `logo`, `key_prefix`, `show_graph`,...)

**Comment by kkozlik** [comment]
cannot reproduce
